/* =====================================================================
   CanchApp Arauca — Catálogo de canchas (datos de ejemplo)
   ---------------------------------------------------------------------
   Coordenadas aproximadas dentro de la ciudad de Arauca, Arauca (CO).
   Reemplaza estos datos por los reales de cada cancha:
   nombre, dirección, barrio, teléfono (WhatsApp), precio y horario.
   El teléfono se usa para confirmar la reserva por WhatsApp.
   ===================================================================== */
window.CANCHAS = [
  {
    id: "c1",
    nombre: "Cancha Meridiano 70",
    tipo: "sintetica",              // "futsal" | "sintetica"
    barrio: "Meridiano 70",
    direccion: "Cra. 22 con Calle 18",
    lat: 7.0912, lng: -70.7568,
    telefono: "573001112233",       // formato 57 + celular (ejemplo)
    precioHora: 90000,
    jugadores: "8 vs 8",
    horaApertura: 8, horaCierre: 23, // 24h
    iluminada: true, techada: false,
    rating: 4.7, resenas: 128,
    servicios: ["Parqueadero", "Baños", "Tienda", "Graderías"],
    color: "#0b6e4f",
  },
  {
    id: "c2",
    nombre: "Futsal Centro Arena",
    tipo: "futsal",
    barrio: "Centro",
    direccion: "Calle 20 # 19-40",
    lat: 7.0846, lng: -70.7597,
    telefono: "573002223344",
    precioHora: 60000,
    jugadores: "5 vs 5",
    horaApertura: 9, horaCierre: 22,
    iluminada: true, techada: true,
    rating: 4.9, resenas: 210,
    servicios: ["Techada", "Baños", "Hidratación", "Aire"],
    color: "#1e6091",
  },
  {
    id: "c3",
    nombre: "Cancha La Esperanza",
    tipo: "sintetica",
    barrio: "La Esperanza",
    direccion: "Cra. 30 # 12-15",
    lat: 7.0789, lng: -70.7521,
    telefono: "573003334455",
    precioHora: 80000,
    jugadores: "7 vs 7",
    horaApertura: 8, horaCierre: 23,
    iluminada: true, techada: false,
    rating: 4.4, resenas: 76,
    servicios: ["Parqueadero", "Baños", "Graderías"],
    color: "#2d6a4f",
  },
  {
    id: "c4",
    nombre: "Complejo 20 de Julio",
    tipo: "sintetica",
    barrio: "20 de Julio",
    direccion: "Av. Olaya # 8-90",
    lat: 7.0881, lng: -70.7642,
    telefono: "573004445566",
    precioHora: 100000,
    jugadores: "8 vs 8",
    horaApertura: 7, horaCierre: 23,
    iluminada: true, techada: false,
    rating: 4.6, resenas: 154,
    servicios: ["Parqueadero", "Baños", "Tienda", "Graderías", "Árbitro"],
    color: "#40916c",
  },
  {
    id: "c5",
    nombre: "Futsal El Bosque",
    tipo: "futsal",
    barrio: "El Bosque",
    direccion: "Cra. 24 # 25-10",
    lat: 7.0803, lng: -70.7648,
    telefono: "573005556677",
    precioHora: 55000,
    jugadores: "5 vs 5",
    horaApertura: 9, horaCierre: 22,
    iluminada: true, techada: true,
    rating: 4.3, resenas: 61,
    servicios: ["Techada", "Baños", "Hidratación"],
    color: "#3a86ff",
  },
  {
    id: "c6",
    nombre: "Cancha Las Corocoras",
    tipo: "sintetica",
    barrio: "Las Corocoras",
    direccion: "Cra. 15 # 30-22",
    lat: 7.0938, lng: -70.7503,
    telefono: "573006667788",
    precioHora: 85000,
    jugadores: "7 vs 7",
    horaApertura: 8, horaCierre: 23,
    iluminada: true, techada: false,
    rating: 4.5, resenas: 98,
    servicios: ["Parqueadero", "Baños", "Tienda"],
    color: "#52b788",
  },
  {
    id: "c7",
    nombre: "Arena Los Libertadores",
    tipo: "futsal",
    barrio: "Los Libertadores",
    direccion: "Calle 12 # 28-05",
    lat: 7.0762, lng: -70.7585,
    telefono: "573007778899",
    precioHora: 65000,
    jugadores: "6 vs 6",
    horaApertura: 9, horaCierre: 23,
    iluminada: true, techada: true,
    rating: 4.8, resenas: 143,
    servicios: ["Techada", "Baños", "Hidratación", "Graderías"],
    color: "#7048e8",
  },
  {
    id: "c8",
    nombre: "Cancha Córdoba",
    tipo: "sintetica",
    barrio: "Córdoba",
    direccion: "Av. Ganadera # 4-30",
    lat: 7.0854, lng: -70.7480,
    telefono: "573008889900",
    precioHora: 75000,
    jugadores: "7 vs 7",
    horaApertura: 8, horaCierre: 22,
    iluminada: true, techada: false,
    rating: 4.2, resenas: 54,
    servicios: ["Parqueadero", "Baños"],
    color: "#e8590c",
  },
  {
    id: "c9",
    nombre: "Estadio Sintético La Unión",
    tipo: "sintetica",
    barrio: "La Unión",
    direccion: "Cra. 40 # 20-60",
    lat: 7.0916, lng: -70.7699,
    telefono: "573009990011",
    precioHora: 110000,
    jugadores: "9 vs 9",
    horaApertura: 7, horaCierre: 23,
    iluminada: true, techada: false,
    rating: 4.9, resenas: 187,
    servicios: ["Parqueadero", "Baños", "Tienda", "Graderías", "Árbitro", "Camerinos"],
    color: "#c9184a",
  },
];
